### ISSUE TITLE
Corriger le bug dans la 0.07.1

### ISSUE THREAD

**Issue by navet56** [jlppc/Projet-Pokemon-Regimys#14]
//Pour creer une issue de bug, merci de suivre la forme suivante.
# Description du bug et explication du moment ou il est survenu: Au demarrage du jeu, ce message apparrait : "aucun attribut manifest principal dans regimys.jar"

# Log.txt ou lien vers le fichier :

# CrashLog.txt ou lien vers le fichier :

//Pour creer une issue d'update, merci de suivre la forme suivante.
# Fonctionnalité a améliorer :

# Description de l'ajout :

//Pour creer tout autre forme d'Issue, faites comme vous voulez, mais soyez clair, compréhesible et précis.
//Veuillez supprimer toutes les lignes commencant par //

**Comment by jlppc** [comment]
Fermeture de l'issue due a sa description incorrecte
Hé oui ca vaut pour tout le monde, toi aussi!
